### ISSUE TITLE
Also patch java-objc-bridge

### ISSUE THREAD

**Issue by ryanccn** [Dreamail/M1MC#1]
One thing that I noticed is that the TTS engine in Minecraft uses `ca.weblite.java-objc-bridge`, which in version 1.1 supports macOS arm64 but the version Minecraft uses is 1.0.0.

So I was wondering if you could also patch this library along with LWJGL, since without patching the TTS engine fails to initialize and throws an error.

[Maven](https://mvnrepository.com/artifact/ca.weblite/java-objc-bridge/1.1)
[java-objc-bridge-1.1.tar.gz](https://github.com/Dreamail/M1MC/files/8189952/java-objc-bridge-1.1.tar.gz)

**Comment by ryanccn** [comment]
It also uses `libjcocoa.dylib`

**Comment by Dreamail** [comment]
I will add support for it if I have free time.(I am a senior high student. XD

Also, pr is welcome.

**Comment by ryanccn** [comment]
lol I'm a middle school student

I don’t know any Go except the very basics so I can’t understand one single line of the code 😂

But does the executable basically just add the m1mc libs to the classpath?

**Comment by Dreamail** [comment]
> lol I'm a middle school student
> 
> I don’t know any Go except the very basics so I can’t understand one single line of the code 😂
> 
> But does the executable basically just add the m1mc libs to the classpath?

Yes. It just replace the original native libraries and jar with arm64 ones.

**Comment by ryanccn** [comment]
Hello, um can you release the new version

**Comment by Dreamail** [comment]
oh, I have forgot it. I have done my code but now I trapped in school.😭

**Comment by ryanccn** [comment]
which city are you in?

**Comment by Dreamail** [comment]
> which city are you in?

Qinzhou, Guangxi 🤣

**Comment by ryanccn** [comment]
Oh... I'm in Shanghai
